server:
  port: 80

spring:
  application:
    name: cloud-payment-order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://activate.navicat.com:7002/eureka/,http://localhost:7001/eureka/