server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: guan123456
  # 在eureka注册中心显示的名称
  application:
    name: cloud-payment

eureka:
  client:
    # 表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须为true
    fetch-registry: true
    service-url:
      # 注册中心的ip地址端口号,使用集群用（,）隔开
#      defaultZone: http://activate.navicat.com:7002/eureka/,http://localhost:7001/eureka/
     defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    # 租约过期时间，单位为秒
#    lease-expiration-duration-in-seconds: 1
    # 租约更新时间，单位为秒
#    lease-renewal-interval-in-seconds: 2

mybatis-plus:
  # 扫描mapper文件
  mapper-locations: classpath:mapper/*.xml